import type { Metadata } from "next";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs"
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html
      lang="en" >
      <body className="min-h-full flex flex-col">
        <ThemeProvider 
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
              <Toaster />
          {children}
          
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
